name: Deploy static site to OVH Web Cloud

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to OVH Web Hosting
        uses: guitdev/OVHcloud-deploy-hosting-action@v1
        with:
          ssh_host: ${{ secrets.OVH_HOST }}
          ssh_user: ${{ secrets.OVH_USER }}
          ssh_key: ${{ secrets.OVH_KEY }}
          local_path: "."
          remote_path: ${{ secrets.OVH_PATH }}
